//
//
//require.config({
//  "paths": {
//    "angular": "bower_components/angular/angular",
//    "angular-animate": "bower_components/angular-animate/angular-animate",
//    "angular-cookies": "bower_components/angular-cookies/angular-cookies",
//    "angular-sanitize": "bower_components/angular-sanitize/angular-sanitize",
//    "jquery": "bower_components/jquery/dist/jquery",
//    "angular-ui-router": "bower_components/angular-ui-router/release/angular-ui-router",
//    "angular-bootstrap": "bower_components/angular-bootstrap/ui-bootstrap-tpls",
//    "malarkey": "bower_components/malarkey/dist/malarkey.min",
//    "toastr": "bower_components/toastr/toastr",
//    "angular-elastic": "bower_components/angular-elastic/elastic",
//    "ng-tags-input": "bower_components/ng-tags-input/ng-tags-input.min",
//    "angular-ui-tree": "bower_components/angular-ui-tree/dist/angular-ui-tree",
//    "firebase": "bower_components/firebase/firebase",
//    "angularfire": "bower_components/angularfire/dist/angularfire",
//    "cryptojslib": "bower_components/cryptojslib/rollups/sha1",
//    "moment": "bower_components/moment/moment",
//    "angular-moment": "bower_components/angular-moment/angular-moment",
//    "angular-aria": "bower_components/angular-aria/angular-aria",
//    "angular-material": "bower_components/angular-material/angular-material",
//    "angular-material-icons": "bower_components/angular-material-icons/angular-material-icons.min",
//    "angular-resource": "bower_components/angular-resource/angular-resource",
//    "socket.io.client": "bower_components/socket.io.client/dist/socket.io-1.3.5",
//    "angular-socket-io": "bower_components/angular-socket-io/socket",
//    "ng-lodash": "bower_components/ng-lodash/build/ng-lodash", /*BEGIN_APPDEPS*/
//    "dynamic.modules": "app/dynamic.modules",
//    "index.config": "app/index.config",
//    "index.constants": "app/index.constants",
//    "index.module": "app/index.module",
//    "index.route": "app/index.route",
//    "index.run": "app/index.run",
//    "chatter.Bootstrap": "app/chatter/chatter.Bootstrap",
//    "chatter.controller.consoleChatter": "app/chatter/chatter.controller.consoleChatter",
//    "chatter.controller.modalInstance": "app/chatter/chatter.controller.modalInstance",
//    "chatter.controller.tablecell": "app/chatter/chatter.controller.tablecell",
//    "chatter.directive.focusMe": "app/chatter/chatter.directive.focusMe",
//    "chatter.directive.morphInput": "app/chatter/chatter.directive.morphInput",
//    "chatter.directive.obiChatterEnable": "app/chatter/chatter.directive.obiChatterEnable",
//    "chatter.directive.obiTable": "app/chatter/chatter.directive.obiTable",
//    "chatter.directive.obiTableCell": "app/chatter/chatter.directive.obiTableCell",
//    "chatter.directive.topic": "app/chatter/chatter.directive.topic",
//    "chatter.filters": "app/chatter/chatter.filters",
//    "chatter.module": "app/chatter/chatter.module",
//    "chatter.services": "app/chatter/chatter.services",
//    "common.directive.paletteBackground": "app/common/common.directive.paletteBackground",
//    "main.controller": "app/main/main.controller",
//    "main.controller.spec": "app/main/main.controller.spec",
//    "chatter.directive.chatter-feed": "app/chatter/chatter-feed/chatter.directive.chatter-feed",
//    "chatter.service.comment-api": "app/chatter/services/chatter.service.comment-api",
//    "chatter.service.socket-factory": "app/chatter/services/chatter.service.socket-factory",
//    "chatter.service.state": "app/chatter/services/chatter.service.state",
//    "chatter.service.topic-api": "app/chatter/services/chatter.service.topic-api",
//    "chatter.service.topic": "app/chatter/services/chatter.service.topic",
//    "chatter.controller.context-chatter-dialog": "app/chatter/contextChatterDialog/chatter.controller.context-chatter-dialog",
//    "chatter.directive.obiSideNavButton": "app/chatter/sideNav/chatter.directive.obiSideNavButton",
//    "chatter.directive.sideNav": "app/chatter/sideNav/chatter.directive.sideNav",
//    "sha1": "app/components/cryptojs/sha1",
//    "malarkey.directive": "app/components/malarkey/malarkey.directive",
//    "githubContributor.service": "app/components/githubContributor/githubContributor.service",
//    "navbar.directive": "app/components/navbar/navbar.directive",
//    "webDevTec.service": "app/components/webDevTec/webDevTec.service",
//    "css": "app/components/CSSLoader/dist/css" /*END_APPDEPS*/
//  },
//  "shim": {
//    "angular": {"deps": ["jquery"], "exports": "angular"},
//    "angular-animate": {"deps": ["angular"]},
//    "angular-cookies": {"deps": ["angular"]},
//    "angular-sanitize": {"deps": ["angular"]},
//    "jquery": {"deps": []},
//    "angular-ui-router": {"deps": ["angular"]},
//    "angular-bootstrap": {"deps": ["angular"]},
//    "malarkey": {"deps": []},
//    "toastr": {"deps": ["jquery"]},
//    "animate.css": {"deps": []},
//    "angular-elastic": {"deps": ["angular"]},
//    "ng-tags-input": {"deps": ["angular"]},
//    "angular-ui-tree": {"deps": ["angular"]},
//    "firebase": {"deps": []},
//    "angularfire": {"deps": ["angular", "firebase"]},
//    "components-font-awesome": {"deps": []},
//    "cryptojslib": {"deps": []},
//    "moment": {"deps": []},
//    "angular-moment": {"deps": ["angular", "moment"]},
//    "angular-aria": {"deps": ["angular"]},
//    "angular-material": {"deps": ["angular", "angular-animate", "angular-aria"]},
//    "angular-material-icons": {"deps": ["angular"]},
//    "salesforce-lightning-design-system": {"deps": []},
//    "angular-resource": {"deps": ["angular"]},
//    "socket.io.client": {"exports": "io"},
//    "angular-socket-io": {"deps": ["angular", "socket.io.client"]},
//    "ng-lodash": {"deps": ["angular"]}, /*BEGIN_APPSHIM*/
//    "dynamic.modules": {"deps": ["angular"]},
//    "index.config": {"deps": ["angular"]},
//    "index.constants": {"deps": ["angular"]},
//    "index.module": {"deps": ["angular"]},
//    "index.route": {"deps": ["angular"]},
//    "index.run": {"deps": ["angular"]},
//    "test": {"deps": ["angular"]},
//    "chatter.Bootstrap": {"deps": ["angular"]},
//    "chatter.controller.consoleChatter": {"deps": ["angular"]},
//    "chatter.controller.modalInstance": {"deps": ["angular"]},
//    "chatter.controller.tablecell": {"deps": ["angular"]},
//    "chatter.directive.focusMe": {"deps": ["angular"]},
//    "chatter.directive.morphInput": {"deps": ["angular"]},
//    "chatter.directive.obiChatterEnable": {"deps": ["angular"]},
//    "chatter.directive.obiTable": {"deps": ["angular"]},
//    "chatter.directive.obiTableCell": {"deps": ["angular"]},
//    "chatter.directive.topic": {"deps": ["angular"]},
//    "chatter.filters": {"deps": ["angular"]},
//    "chatter.module": {"deps": ["angular"]},
//    "chatter.services": {"deps": ["angular"]},
//    "common.directive.paletteBackground": {"deps": ["angular"]},
//    "main.controller": {"deps": ["angular"]},
//    "main.controller.spec": {"deps": ["angular"]},
//    "chatter.directive.chatter-feed": {"deps": ["angular"]},
//    "chatter.service.comment-api": {"deps": ["angular"]},
//    "chatter.service.socket-factory": {"deps": ["angular"]},
//    "chatter.service.state": {"deps": ["angular"]},
//    "chatter.service.topic-api": {"deps": ["angular"]},
//    "chatter.service.topic": {"deps": ["angular"]},
//    "chatter.controller.context-chatter-dialog": {"deps": ["angular"]},
//    "chatter.directive.obiSideNavButton": {"deps": ["angular"]},
//    "chatter.directive.sideNav": {"deps": ["angular"]},
//    "sha1": {"deps": ["angular"]},
//    "malarkey.directive": {"deps": ["angular"]},
//    "githubContributor.service": {"deps": ["angular"]},
//    "navbar.directive": {"deps": ["angular"]},
//    "webDevTec.service": {"deps": ["angular"]},
//    "css": {"deps": ["angular"]} /*END_APPSHIM*/
//  }
//});
//
//declare module 'index.module' {
//}
//# sourceMappingURL=app-config.js.map